args={}
kwargs={}
args['batch_size']=500
args['test_batch_size']=500
args['epochs']=5  #The number of Epochs is the number of times you go through the full dataset.
args['lr']=0.005 #Learning rate is how fast it will decend.
args['seed']=1 #random seed
args['log_interval']=20
args['cuda']=False